export function FooterBlock({ block, onEdit }) {
  return (
    <footer className="w-full bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 dark:from-black dark:via-slate-900 dark:to-black text-white py-20 px-6 relative overflow-hidden transition-colors">
      {/* Gradient line top */}
      <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-blue-500 via-indigo-500 to-blue-500"></div>

      {/* Decorative elements */}
      <div className="absolute top-10 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl"></div>
      <div className="absolute bottom-10 left-0 w-48 h-48 bg-indigo-500/10 rounded-full blur-3xl"></div>

      <div className="max-w-6xl mx-auto relative z-10">
        {/* Content grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-12 pb-12 border-b border-white/10">
          {/* About */}
          <div>
            <h3 className="text-lg font-bold mb-4">About</h3>
            <p className="text-gray-400 leading-relaxed">
              AI-powered landing page generator designed to help you create beautiful web pages in seconds.
            </p>
          </div>

          {/* Features */}
          <div>
            <h3 className="text-lg font-bold mb-4">Features</h3>
            <ul className="space-y-2 text-gray-400">
              <li className="hover:text-white transition-colors">✓ Instant Generation</li>
              <li className="hover:text-white transition-colors">✓ Fully Editable</li>
              <li className="hover:text-white transition-colors">✓ AI Powered</li>
            </ul>
          </div>

          {/* Contact */}
          <div>
            <h3 className="text-lg font-bold mb-4">Contact</h3>
            <p className="text-gray-400 leading-relaxed">
              {block.text}
            </p>
          </div>
        </div>

        {/* Footer bottom */}
        <div className="flex flex-col sm:flex-row justify-between items-center pt-8">
          <div className="text-sm text-gray-400">
            <p>© {new Date().getFullYear()} Landing Page Generator. All rights reserved.</p>
          </div>
          <button
            onClick={() => onEdit('Footer', block)}
            className="mt-4 sm:mt-0 inline-flex items-center gap-2 px-6 py-2 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-lg transition-all border border-white/20"
          >
             Edit Footer
          </button>
        </div>

        {/* Generated by note */}
        <div className="text-center mt-8 pt-8 border-t border-white/10">
          <p className="text-sm text-gray-500">
            Generated with <span className="text-blue-400 font-bold">AI Landing Page Generator</span>
          </p>
        </div>
      </div>
    </footer>
  );
}